/* C:\BORLANDC\MONMENU.H 9/15/1992 20:09*/
#define  IDM_NEW	1
#define  IDM_LOAD	2
#define  IDM_SAVE	3
#define  IDM_EXIT	4
#define  IDM_BUYLAND	5
#define  IDM_SELLLAND	6
#define  IDM_MORTGAGE	7
#define  IDM_UNMORTGAGE	8
#define  IDM_SEECARD	9
#define  IDM_BUYHOUSE	10
#define  IDM_SELLHOUSE	11
#define  IDM_HELP	12
#define  IDM_ABOUT	14
#define  IDM_HISCORE	13
#define  IDM_SPEED	15
#define  IDM_AUCTION	16
#define  IDM_RULES	17
#define  IDM_HOWTOPLAY	18
